services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=devices'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=localuser'
      - 'POSTGRES_SERVER=localhost'
    ports:
      - '5432'
